### ISSUE TITLE
Deprecated features used

### ISSUE THREAD

**Issue by slyness** [sous-chefs/graphite#248]
along with #238 

attention: `Using an LWRP provider by its name (GraphiteServiceRunit) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.`

```
       Deprecated features used!
         Cannot specify both default and name_property together on property name of resource graphite_carbon_aggregator. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/carbon_aggregator.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property name of resource graphite_carbon_cache. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/carbon_cache.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property name of resource graphite_carbon_conf_accumulator. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/carbon_conf_accumulator.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property name of resource graphite_carbon_relay. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/carbon_relay.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property name of resource graphite_service. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/service.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property prefix of resource graphite_storage. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/storage.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property name of resource graphite_storage_conf_accumulator. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/storage_conf_accumulator.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property name of resource graphite_storage_schema. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/storage_schema.rb:23:in `class_from_file'
         Cannot specify both default and name_property together on property path of resource graphite_web_config. Only one (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from the property. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/web_config.rb:22:in `class_from_file'
         Using an LWRP provider by its name (GraphiteServiceRunit) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead. at 1 location:
           - /tmp/kitchen/cache/cookbooks/graphite/resources/service.rb:27:in `initialize'
```

**Comment by damacus** [comment]
Relates to #238 #274
