### ISSUE TITLE
twisted cannot install due to the location the location does not exist

### ISSUE THREAD

**Issue by joshoohaah** [sous-chefs/graphite#251]
running graphite v1.0.4 version of the cookbook, and running into this issue where python-pip can't download/install "twisted" due to the fact the location doesn't exist.   (side note: the python cookbook this cookbook uses is deprecated and urging people to update using this cookbook now: https://github.com/poise/poise-python)

```
       Recipe: graphite::_carbon_packages
         * python_pip[Twisted] action install

           ================================================================================
           Error executing action `install` on resource 'python_pip[Twisted]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - pip

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:158:in `pip_cmd'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:139:in `install_package'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:46:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/python/providers/pip.rb:44:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/graphite/recipes/_carbon_packages.rb

            24: python_pip 'Twisted' do
            25:   version lazy { node['graphite']['twisted_version'] }
            26: end
            27:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/graphite/recipes/_carbon_packages.rb:24:in `from_file'

           python_pip("Twisted") do
             action :install
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :python_pip
             cookbook_name "graphite"
             recipe_name "_carbon_packages"
             version #<Chef::DelayedEvaluator:0x00000003a2a2d0@/tmp/kitchen/cache/cookbooks/graphite/recipes/_carbon_packages.rb:25>
             package_name "Twisted"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by TraGicCode** [comment]
I am running into this same issue.

**Comment by pauldambra** [comment]
Did either of you resolve this? 🙏

**Comment by TraGicCode** [comment]
Nope

**Comment by luckymike** [comment]
I suspect this is entirely related to using the old python cookbook, as it sounds like pip is straight-up missing on the system.

**Comment by pauldambra** [comment]
yeah, I vendored the cookbook and switched to poise-python. still needed to actually install pip before it would work though (which the poise-python issues discussions suggested wasn't necessary). 

I'll open a PR later. Relatively small change but I'm pretty new to chef so it'll definitely be a PR to start a conversation rather than a finished product :)

**Comment by pauldambra** [comment]
Hmmm, I 
* grabbed latest 
* ran `bundle install`
* ran `bundle exec rake unit`

received several failing tests with output

```
Failure/Error: let(:chef_run) { runner.converge(described_recipe) }
     RuntimeError:
       This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.
```

but if I 
```
➜  graphite git:(develop) ✗ chef-client --version
/Users/coding/.rvm/gems/ruby-2.3.0/gems/chef-11.18.12/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Chef: 11.18.12
```

however I have Chef 12.x installed.

Am I being silly? Have I missed something?

**Comment by pauldambra** [comment]
Oh, I've got some rvm setup crazy going on

```
➜  graphite git:(develop) ✗ chef --version
Chef Development Kit Version: 0.15.16
chef-client version: ERROR
delivery version: master (444effdf9c81908795e88157f01cd667a6c43b5f)
berks version: 4.3.5
kitchen version: ERROR
```

then

```
➜  graphite git:(develop) ✗ rvm use system
Now using system ruby.
➜  graphite git:(develop) ✗ chef --version
Chef Development Kit Version: 0.15.16
chef-client version: 12.11.18
delivery version: master (444effdf9c81908795e88157f01cd667a6c43b5f)
berks version: 4.3.5
kitchen version: 1.10.0
➜  graphite git:(develop) ✗ chef-client --version
Chef: 12.11.18
```

**Comment by pauldambra** [comment]
Ah, no I think it's cos the gemfile is locked to v 3.3.0 of ChefSpec which is locked to v11 of Chef. I think I'm passing out of the "I think this could be a quick PR to help out" phase, sorry

**Comment by damacus** [comment]
Looks like it's related to #275 python being deprecated and pretty broken at this point.

**Comment by damacus** [comment]
I'm going to get a chance to take a look at this in the next few weeks.

**Comment by t2y** [comment]
I tested in my environment (centos 7.3) without pip.

An error occurred when I set only "recipe[graphite::_carbon_packages]" as run_list, then converge it.

```
Recipe: graphite::_carbon_packages
  * python_package[Twisted] action install[2017-04-29T12:35:20+09:00] INFO: Processing python_package[Twisted] action install (graphite::_carbon_packages line 24) 

  
    ====================================================================
    Error executing action `install` on resource 'python_package[Twisted]'
    ====================================================================
        
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1' 
    ---- Begin output of ["/usr/bin/python", "-m", "pip.__main__", "list"] ----
    STDOUT: 
    STDERR: /usr/bin/python: No module named pip 
    ---- End output of ["/usr/bin/python", "-m", "pip.__main__", "list"] ----
    Ran ["/usr/bin/python", "-m", "pip.__main__", "list"] returned 1
        
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:207:in `tap'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:207:in `language_command_shell_out!'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:222:in `block in language_command_mixin'
    /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:317:in `pip_command'
    /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:203:in `check_package_versions'
    /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:189:in `load_current_resource'
        
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/graphite/recipes/_carbon_packages.rb
        
     24: python_package 'Twisted' do
     25:   version lazy { node['graphite']['twisted_version'] }
     26: end 
     27:
```

**Comment by t2y** [comment]
But, there's no error when I set "recipe[graphite::carbon]" as run_list, then converge it. Because `options pip_version: true` is set and `python_runtime` resource will install pip if it's not found.

```ruby
python_runtime 'carbon' do
  provider :system
  version '2.7'
  options pip_version: true
end
```

`poise_python` installs pip by getting pypa.io.

```
* python_runtime_pip[carbon] action install[2017-04-29T12:41:36+09:00] INFO: Processing python_runtime_pip[carbon] action install (/var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb line 118)
 
  - Bootstrapping pip latest from https://bootstrap.pypa.io/get-pip.py
```

**Comment by t2y** [comment]
@damacus I think we can close this issue. What do you think about my verification above?

**Comment by damacus** [comment]
If that works for you. That's great. We have a way to move forward. 

I'll remember that when I come to rework the cookbook. 

Thanks @t2y
